

SUBROUTINE INDEXALE
USE VARIABLE,ONLY: N1DA_ALE,NN_ALE,IA_ALE,JA_ALE,NE_ALE,NODEELE_ALE
IMPLICIT NONE

INTEGER:: I,J,M,K,MM,NK,L,L1,NODEOLD,NODE,NAA,IG,IP 
INTEGER:: IN,MI,II,JEMP,NNN,ERR,NET(4),NQ,KK
INTEGER,ALLOCATABLE:: JMEN(:), NEN(:,:), J2(:),NENQ(:,:),I4ARRAY(:)

ALLOCATE(JMEN(NN_ALE),J2(NN_ALE),IA_ALE(NN_ALE+1),I4ARRAY(NN_ALE*20))
ALLOCATE(NENQ(10,NN_ALE))


N1DA_ALE=0
NNN =0
JMEN=0
NEN =0   

DO I=1,NE_ALE 
NET(:)=NODEELE_ALE(I,:)              
	DO J=1,4                
	MM=NET(J) 	   
	JMEN(MM)=JMEN(MM)+1      
	NK=JMEN(MM)                        
		IF(NK>10) THEN
		WRITE(*,*)' EM9' 
		WRITE(*,*) NK,MM
		PAUSE
        STOP
		END IF
	NENQ(NK,MM)=I	
	END DO
END DO 

IA_ALE(1)=1   
DO I=1,NN_ALE                                                               
IG=0
NQ=JMEN(I)       ! NUMBER OF SURROUNDING ELEMENTS
	DO J=1,NQ
	NK=NENQ(J,I) ! ELEMENT INDEX
	NET(:)=NODEELE_ALE(NK,:)
		DO K=1,4
		L=NET(K)
			IF (L<=I) THEN
			IG=IG+1	
!				IF(IG>=20) THEN; WRITE(*,*) 'IG20'; STOP; END IF
			J2(IG)=L  
			END IF
		END DO
	END DO

  
	DO M=1,IG-1                                                   
		DO L=M+1,IG                                                      
			IF(J2(M)==J2(L)) THEN
			J2(M)=0
			END IF 
		END DO
	END DO
		
	IN=0	   
	DO J=1,IG
		IF(J2(J)/=0) THEN      
		IN=IN+1 
		J2(IN)=J2(J) 
		END IF
	END DO
          
	M=IN-1
	DO K=1,M
		DO KK=K+1,IN
			IF( J2(K) .GE. J2(KK) ) THEN 
			JEMP=J2(K)
			J2(K)=J2(KK)
			J2(KK)=JEMP
			END IF 
		END DO
	END DO 
	      
	IA_ALE(I+1)=IA_ALE(I)+IN
	MI=IA_ALE(I)-1 
	 
	DO II=1,IN      
	NAA=MI+II
	N1DA_ALE=N1DA_ALE+1
	I4ARRAY(NAA)=J2(II)
	IF(NAA/=N1DA_ALE) THEN
        WRITE(*,*) ' RC5M'
        PAUSE
        STOP
    END IF
        
	END DO
END DO

IF(NAA+1/=IA_ALE(NN_ALE+1)) THEN
WRITE(*,*) NAA,N1DA_ALE,IA_ALE(NN_ALE+1)
WRITE(*,*) ' BFGF'
PAUSE
STOP
END IF

ALLOCATE(JA_ALE(N1DA_ALE))
JA_ALE(1:N1DA_ALE)=I4ARRAY(1:N1DA_ALE)
DEALLOCATE(I4ARRAY)

WRITE(*,'(A10,I12)')'1D ARRAY =',N1DA_ALE
END SUBROUTINE INDEXALE
!
!
!
!
!
SUBROUTINE COEFFICIENTMATRIXALE
USE VARIABLE!,ONLY:  NE_ALE,NODEELE_ALE,X_ALE,Y_ALE,IA_ALE,JA_ALE,WEI,XPDKSI11,YPDITA22,XPDITA21, &
				!YPDKSI12 ,FPDX,FPDY, FPDKSI,FPDITA,AP_ALE
IMPLICIT NONE

INTEGER :: I,J,K,L,M,IE,NET(4),NK,NAF1,NAF2,JJ,NAF,MM,NPP
REAL(8) :: A1(4,4),A2(10),FD,Q,F1(4),ROU

INTEGER:: NPE
REAL(8):: XE(5),YE(5),SE

DO  IE=1,NE_ALE
	A1=0.0D0
	NET(1:4)=NODEELE_ALE(IE,1:4)!结点
		
	NPE=5
	XE(1:4)=X_ALE(NET(1:4))  
    YE(1:4)=Y_ALE(NET(1:4))
    XE(5)=XE(1) 
    YE(5)=YE(1) 
	  
	DO  I=1,2  
		DO  J=1,2				
			CALL GAUSS_JACOB_ALE(I,J,IE)		
			FD=XPDKSI11*YPDITA22-XPDITA21*YPDKSI12		!J雅可比矩阵	      
			IF  ( FD < 0.0D0) THEN 
				WRITE(*,*)' ERROR : IE=',IE      
					DO K=1,4                       
					L=NET(K)                     
					WRITE(*,*) L,X_ALE(L),Y_ALE(L)  
                    END DO        
				WRITE(*,*) I,J,XPDKSI11,YPDITA22,XPDITA21,YPDKSI12,FD 
			END IF 
   
			Q=FD*WEI(I)*WEI(J)   

			DO K=1,4		   
			FPDX(K)=(YPDITA22*FPDKSI(I,J,K)-YPDKSI12*FPDITA(I,J,K))/FD
			FPDY(K)=(XPDKSI11*FPDITA(I,J,K)-XPDITA21*FPDKSI(I,J,K))/FD
			END DO

			DO  K=1,4
				DO L=1,4
				A1(K,L)=A1(K,L)+Q*(FPDX(K)*FPDX(L)+FPDY(K)*FPDY(L)) !ELEMENTAL COEFFICIENT MATRIX OF POISSON EQUATION泊松方程的单元系数矩阵
				END DO      !乘以Q=FD*WEI(I)*WEI(J)=/J/*HI*HJ -------------------XHL-----------------积分转换----------------
			END DO					
					 
		END DO
    END DO
!		CALL POLYGON_AREA(NPE,XE,YE,SE)              !多边形面积
!		A1=A1*DSQRT(SE)
		
    M = 0
    DO K = 1,4
        IF(NODETYPE(NET(K))==71)THEN
            M = 1
        END IF
    END DO

    IF (M==1)THEN
        A1 = A1 * 1.5
        !PRINT*,'DONE'
    END IF
    
	DO  K=1,4
		M=NET(K) 
		NAF1=IA_ALE(M)
		NAF2=IA_ALE(M+1)-1
		DO L=1,4
		JJ=NET(L)	   
			DO NAF=NAF1,NAF2
			MM=JA_ALE(NAF) 		  
				IF (MM==JJ) THEN
				NPP=NAF
				AP_ALE(NPP)=AP_ALE(NPP)+A1(K,L) ! GLOBAL COEFFICIENT MATRIX OF POISSON EQUATION泊松方程的整体系数矩阵
                END IF
			END DO
		END DO
	END DO

END DO
		   
END SUBROUTINE COEFFICIENTMATRIXALE
!
!
!
!
!
SUBROUTINE GAUSS_JACOB_ALE(I,J,ELENUM)	
USE VARIABLE,ONLY: XPDKSI11,YPDITA22,XPDITA21,YPDKSI12, FPDX,FPDY, FPDKSI,FPDITA, NODEELE_ALE,X_ALE,Y_ALE	 
IMPLICIT NONE
INTEGER:: I,J,K,L,NET(4),ELENUM
REAL(8):: FPDKSIK,FPDITAK,XNEW(4),YNEW(4)

XPDKSI11=0.0D0
XPDITA21=0.0D0
YPDKSI12=0.0D0
YPDITA22=0.0D0

DO K=1,4
NET(K)=NODEELE_ALE( ELENUM,K )
END DO

DO K=1,4
L=NET(K)
XNEW(K)=X_ALE(L)
YNEW(K)=Y_ALE(L)
END DO

DO K=1,4	
FPDKSIK=FPDKSI(I,J,K) 
FPDITAK=FPDITA(I,J,K)
XPDKSI11=XPDKSI11+FPDKSI(I,J,K)*XNEW(K)  
XPDITA21=XPDITA21+FPDITA(I,J,K)*XNEW(K)   
YPDKSI12=YPDKSI12+FPDKSI(I,J,K)*YNEW(K) 
YPDITA22=YPDITA22+FPDITA(I,J,K)*YNEW(K) 
END DO

END SUBROUTINE GAUSS_JACOB_ALE
!
!
!
!
!
SUBROUTINE DISPLACEMENT_ALE_BC
USE VARIABLE,ONLY: X_ALE,Y_ALE,T,XBC_ALE,YBC_ALE,NBN_ALE, BN_ALE, &
				NPBN_ALE,PBN_ALE,NLBN_ALE,LBN_ALE,NDBN_ALE,DBN_ALE,NRBN_ALE,RBN_ALE,NUBN_ALE,UBN_ALE,NSBN_ALE,SBN_ALE ,DIS_ANG,X00 !,FALEBC
USE CONSTANT,ONLY: AMC_ALE,OMG_ALE,IROTA,T_START

IMPLICIT NONE
INTEGER:: I,J,K,NUM
REAL(8):: PI,Y0,X0,XX,YY,THETA1,THETA2,DD,R00,FOmega,SCL

PI=DACOS(-1.0D0)

IF (ALLOCATED(BN_ALE)) DEALLOCATE(BN_ALE)
ALLOCATE(BN_ALE(NLBN_ALE+NRBN_ALE+NUBN_ALE+NDBN_ALE+NPBN_ALE+NSBN_ALE)) 


NUM=0

!===========PIPE=================================================
IF (IROTA==1) THEN

    IF(T>=T_START) THEN
        !THETA1=AMC_ALE*DCOS(OMG_ALE*(T-T_START)+PI/2.0D0)   
        DIS_ANG=AMC_ALE*DCOS(OMG_ALE*(T-T_START)+PI/2.0D0)     !PDD
    ELSE
        !THETA1=0.0D0
        DIS_ANG=0.0D0   !PDD
    END IF

	DO I=1,NPBN_ALE
	NUM=NUM+1
	J=PBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
 	Y0=Y_ALE(J)

    DD=DSQRT(X0*X0+Y0*Y0)
	THETA2=DASIN(Y0/DD)
	IF (X0<0.0D0)   THEN
	    THETA2=PI-THETA2
    END IF

!	    XX=0.0D0					!!!!!!!!!!!!!!!!!!!!!!!
!	    YY=0.0D0            !AMC_ALE*DSIN(OMG_ALE*T)	!!!!!!!!!!!!!!!!!!!!!!!

	! XBC_ALE(NUM)=DD*DCOS(THETA1+THETA2)    !X0+XX
	! YBC_ALE(NUM)=DD*DSIN(THETA1+THETA2)    !Y0+YY
        XBC_ALE(NUM)=DD*DCOS(DIS_ANG+THETA2)    !X0+XX    PDD
	    YBC_ALE(NUM)=DD*DSIN(DIS_ANG+THETA2)    !Y0+YY   PDD


	END DO

ELSE IF (IROTA==10 .OR. IROTA==11 .OR. IROTA==0) THEN

	DO I=1,NPBN_ALE
	NUM=NUM+1
	J=PBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
 	Y0=Y_ALE(J)

    XX=0.0D0
	YY=0.0D0

	XBC_ALE(NUM)=X0+XX
	YBC_ALE(NUM)=Y0+YY
	END DO

ELSE IF (IROTA==2) THEN

	DO I=1,NPBN_ALE
	NUM=NUM+1
	J=PBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
 	Y0=Y_ALE(J)

    DD=DSQRT(X0*X0+Y0*Y0)
	THETA2=DASIN(Y0/DD)
	IF (X0<0.0D0)   THEN
	    THETA2=PI-THETA2
    END IF

    IF(T>=T_START) THEN
	    XBC_ALE(NUM)=DD*DCOS(DIS_ANG+THETA2)
	    YBC_ALE(NUM)=DD*DSIN(DIS_ANG+THETA2)
	ELSE
	    XBC_ALE(NUM)=X0  
	    YBC_ALE(NUM)=Y0
	END IF
	END DO
ELSE IF (IROTA==5107) THEN
    
    DO I=1,NPBN_ALE
        NUM=NUM+1
        J=PBN_ALE(I)
        BN_ALE(NUM)=J
        X0=X_ALE(J)
        Y0=Y_ALE(J)
        
        XBC_ALE(NUM)=X0
        YBC_ALE(NUM)=Y0
    END DO

END IF
!===========PLATE=================================================
IF (IROTA==1) THEN

    IF(T>=T_START) THEN
        !THETA1=AMC_ALE*DCOS(OMG_ALE*(T-T_START)+PI/2.0D0)    
        DIS_ANG=AMC_ALE*DCOS(OMG_ALE*(T-T_START)+PI/2.0D0)    !PDD
    ELSE
        ! THETA1=0.0D0
        DIS_ANG=0.0D0       !PDD
    END IF

	DO I=1,NSBN_ALE
	NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
 	Y0=Y_ALE(J)

	!XBC_ALE(NUM)=X0*DCOS(THETA1)-Y0*DSIN(THETA1)
	!YBC_ALE(NUM)=X0*DSIN(THETA1)+Y0*DCOS(THETA1)
        XBC_ALE(NUM)=X0*DCOS(DIS_ANG)-Y0*DSIN(DIS_ANG)    !PDD
	    YBC_ALE(NUM)=X0*DSIN(DIS_ANG)+Y0*DCOS(DIS_ANG)     !PDD
        
        
	END DO

ELSE IF (IROTA==10)  THEN

    IF(T>=T_START)THEN
        THETA1=DASIN(AMC_ALE*DSIN(OMG_ALE*(T-T_START)))         !------XHL-----板中心位置的位移？？
    ELSE                                                       !------XHL-----应该是隔板绕圆柱体背部一点旋转     而非圆心
        THETA1=0.0D0
    END IF
                   
    DO I=1,NSBN_ALE
    NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
	Y0=Y_ALE(J)
	        
	R00=X0-X00
	XBC_ALE(NUM)=R00*DCOS(THETA1)	                            
	YBC_ALE(NUM)=R00*DSIN(THETA1)
    END DO

ELSE IF (IROTA==11)  THEN                                     !------XHL-----应该是隔板绕圆柱体背部一点旋转     而非圆心

    IF(T>=T_START)THEN
        THETA1=AMC_ALE*DCOS(OMG_ALE*(T-T_START)+PI/2.0D0)         
    ELSE
        THETA1=0.0D0
    END IF

    DO I=1,NSBN_ALE
    NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
	Y0=Y_ALE(J)
	        
	R00=X0-X00
	XBC_ALE(NUM)=R00*DCOS(THETA1)	
	YBC_ALE(NUM)=R00*DSIN(THETA1)
    END DO

ELSE IF (IROTA==0)  THEN

	DO I=1,NSBN_ALE
	NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
 	Y0=Y_ALE(J)

    XX=0.0D0
	YY=0.0D0

	XBC_ALE(NUM)=X0+XX
	YBC_ALE(NUM)=Y0+YY
	END DO

ELSE IF (IROTA==2)  THEN

    DO I=1,NSBN_ALE
    NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
	Y0=Y_ALE(J)

	IF( T>T_START ) THEN 
	    XBC_ALE(NUM)=X0*DCOS(DIS_ANG)-Y0*DSIN(DIS_ANG)
	    YBC_ALE(NUM)=X0*DSIN(DIS_ANG)+Y0*DCOS(DIS_ANG)
	ELSE
		XBC_ALE(NUM)=X0
		YBC_ALE(NUM)=Y0
	END IF

    END DO
ELSE IF (IROTA==5107)  THEN

    DO I=1,NSBN_ALE
    NUM=NUM+1
	J=SBN_ALE(I)
	BN_ALE(NUM)=J
	X0=X_ALE(J)
	Y0=Y_ALE(J)

    
    FOmega =1.5D0
    SCL  =0.1
	IF( T>T_START ) THEN 
	    XBC_ALE(NUM)=X0
        
        X0 = X0 -0.5D0
	    YBC_ALE(NUM)=Y0+Dsin(T*SCL)*(Dcosh(FOmega*X0)-Dcos(FOmega*X0)+(Dcos(FOmega)+Dcosh(FOmega))/(Dsin(FOmega)+Dsinh(FOmega))*(Dsin(FOmega*X0)-Dsinh(FOmega*X0)))
	ELSE
		XBC_ALE(NUM)=X0
		YBC_ALE(NUM)=Y0
	END IF

    END DO
END IF
!==========DOWN===================================================

DO I=1,NDBN_ALE
NUM=NUM+1
J=DBN_ALE(I)
BN_ALE(NUM)=J
X0=X_ALE(J)
Y0=Y_ALE(J)
XBC_ALE(NUM)=X0
YBC_ALE(NUM)=Y0
END DO

!=============UP=============

DO I=1,NUBN_ALE
NUM=NUM+1
J=UBN_ALE(I)
BN_ALE(NUM)=J
X0=X_ALE(J)
Y0=Y_ALE(J)
XBC_ALE(NUM)=X0
YBC_ALE(NUM)=Y0
END DO

!=============LEFT============

DO I=1,NLBN_ALE
NUM=NUM+1
J=LBN_ALE(I)
BN_ALE(NUM)=J
X0=X_ALE(J)
Y0=Y_ALE(J)
XBC_ALE(NUM)=X0
YBC_ALE(NUM)=Y0
END DO

!==============RIGHT=========

DO I=1,NRBN_ALE
NUM=NUM+1
J=RBN_ALE(I)
BN_ALE(NUM)=J
X0=X_ALE(J)
Y0=Y_ALE(J)
XBC_ALE(NUM)=X0
YBC_ALE(NUM)=Y0
END DO

IF(NUM/=NBN_ALE) THEN
PRINT*, ' GHY6'
PAUSE
STOP
END IF
END SUBROUTINE DISPLACEMENT_ALE_BC
!
!
!
!
!
SUBROUTINE APPLYING_BC1( AAA,BBB,BC1 )          !没看
USE VARIABLE,ONLY: N1DA_ALE,IA_ALE,JA_ALE,NN_ALE,BN_ALE,NBN_ALE

IMPLICIT NONE

INTEGER     :: I,NN,SHBW,EHBW,J,K,NUM_LEFT_UP,NUM_C,NUMBC1,KK
REAL(KIND=8):: H,GCM_VALUE,AAA(N1DA_ALE),BBB(NN_ALE),BC1(NBN_ALE)


NUMBC1=NBN_ALE


DO  I=1,NUMBC1
	NN=BN_ALE(I)
	SHBW=IA_ALE(NN) 
	EHBW=IA_ALE(NN+1)-1

	AAA(EHBW)=1.0D0
	H=BC1(I)
	BBB(NN)=H

	NUM_LEFT_UP=IA_ALE(NN+1)-1-IA_ALE(NN)
	KK=0

	DO  J=1,NUM_LEFT_UP
		NUM_C              = JA_ALE( IA_ALE(NN)+KK )
		GCM_VALUE          = AAA( IA_ALE(NN)+KK )
		BBB(NUM_C)         = BBB( NUM_C )-GCM_VALUE*H
		AAA(IA_ALE(NN)+KK) = 0.0D0
		KK                 = KK+1
	END DO

	IF (NN /= NN_ALE) THEN
		DO  J=NN+1,NN_ALE   
			DO  K=IA_ALE(J), IA_ALE(J+1)-1
				IF ( JA_ALE(K)==NN ) THEN 
					GCM_VALUE = AAA(K)
					BBB(J)    = BBB(J)-GCM_VALUE*H
					AAA(K)    = 0.0D0
				END IF
			END DO
		END DO
	END IF

END DO


END SUBROUTINE APPLYING_BC1





SUBROUTINE SOLUTION_BICGS_ALE(AAA,BBB,XXX)      !没看
USE VARIABLE, ONLY: N1DA_ALE,NN_ALE,IA_ALE,JA_ALE
IMPLICIT NONE

REAL(8):: AAA(N1DA_ALE),BBB(NN_ALE),XXX(NN_ALE),EPS_BICGSTAB,ROL,RAQ,ALF,W,ERROR,EPS,ROLI,BATE,WU,WD
INTEGER:: KK,ITERA_MAX,I,J,K

INTEGER,ALLOCATABLE:: IEAPT(:),JEAPT(:)
REAL(8),ALLOCATABLE:: EAP(:),EAPT(:)
REAL(8),ALLOCATABLE:: PI(:),R(:),DRO(:),Y(:),S(:),T(:),Z(:)
REAL(8),ALLOCATABLE:: NIU(:),TEMPARRAY(:),INVE_T(:),INVE_S(:)

ALLOCATE ( IEAPT(NN_ALE+1), JEAPT(N1DA_ALE) )
ALLOCATE ( EAP  (N1DA_ALE), EAPT (N1DA_ALE) )
ALLOCATE ( PI(NN_ALE), R(NN_ALE), DRO(NN_ALE), Y(NN_ALE)    )
ALLOCATE ( S(NN_ALE) , T(NN_ALE), Z(NN_ALE)  , NIU(NN_ALE)  )
ALLOCATE ( TEMPARRAY(NN_ALE), INVE_T(NN_ALE), INVE_S(NN_ALE) )

EPS_BICGSTAB=1.0D-7


	CALL PRECON_GCM_ALE ( AAA,EAP,EAPT,IEAPT,JEAPT )
	KK        = 0
	ITERA_MAX = 500

	TEMPARRAY =0.0D0
	DO I=1,NN_ALE
		DO J=IA_ALE(I),IA_ALE(I+1)-2
		K=JA_ALE(J)
		TEMPARRAY(I)=TEMPARRAY(I)+AAA(J)*XXX(K)    
		TEMPARRAY(K)=TEMPARRAY(K)+AAA(J)*XXX(I)
		END DO
	TEMPARRAY(I)=TEMPARRAY(I)+AAA(IA_ALE(I+1)-1)*XXX(I)
	END DO

	R=BBB-TEMPARRAY;	DRO=R;			PI=0.0D0
	NIU= 0.0D0;			ROL=1.0D0;		ALF=1.0D0 
	W=1.0D0;			ERROR=10.0D0;	KK=0
		

DO KK=1,ITERA_MAX
ROLI=0.0

	DO I=1,NN_ALE
	ROLI=ROLI+R(I)*DRO(I)  
	END DO

	BATE=( ROLI/ROL )*( ALF/W )
	ROL=ROLI  

	DO I=1,NN_ALE
	PI(I)=R(I)+BATE*(PI(I)-W*NIU(I)) 
	END DO		

	CALL CHOLESKY_ALE(Y,PI,0,EAP,EAPT,IEAPT,JEAPT)
		
	NIU=0.0                      
	DO I=1,NN_ALE
		DO J=IA_ALE(I),IA_ALE(I+1)-2
		K=JA_ALE(J)
		NIU(I)=NIU(I)+AAA(J)*Y(K)
		NIU(K)=NIU(K)+AAA(J)*Y(I)
		END DO
	NIU(I)=NIU(I)+AAA(IA_ALE(I+1)-1)*Y(I)
	END DO	

	RAQ=0.0
	DO I=1,NN_ALE
	RAQ=RAQ+DRO(I)*NIU(I)
	END DO

	ALF=ROLI/RAQ 
   
	DO I=1,NN_ALE
	S(I)=R(I)-ALF*NIU(I)    
	END DO
		
	CALL CHOLESKY_ALE(Z,S,0,EAP,EAPT,IEAPT,JEAPT)      
    
	T=0.0    
	DO I=1,NN_ALE
		DO J=IA_ALE(I),IA_ALE(I+1)-2
		K=JA_ALE(J)
		T(I)=T(I)+AAA(J)*Z(K)
		T(K)=T(K)+AAA(J)*Z(I)
		END DO
	T(I)=T(I)+AAA(IA_ALE(I+1)-1)*Z(I)
	END DO
		
			
	CALL CHOLESKY_ALE( INVE_T,T,1,EAP,EAPT,IEAPT,JEAPT ) 	

	CALL CHOLESKY_ALE( INVE_S,S,1,EAP,EAPT,IEAPT,JEAPT ) 
		  
	WU=0.0D0
	WD=0.0D0

	DO I=1,NN_ALE
	WU=WU+INVE_T(I)*INVE_S(I)
	WD=WD+INVE_T(I)*INVE_T(I)
	END DO

	W=WU/WD   

	DO I=1,NN_ALE
	XXX(I)=XXX(I)+ALF*Y(I)+W*Z(I)
	R(I)=S(I)-W*T(I)	
	END DO	
		
	ERROR=0.0D0
	DO I=1,NN_ALE
	ERROR=ERROR+ABS(R(I))
	END DO
	ERROR=ERROR/FLOAT(NN_ALE)	

	IF (ERROR<=EPS_BICGSTAB) THEN
	WRITE(*,'(A10,I12,10X,A10,E12.4  )') 'INTR ALE =',KK   ,'BICG ALE =',ERROR
	EXIT	
	END IF
END DO

IF (ERROR>EPS_BICGSTAB) THEN
	WRITE(*,*)
	WRITE(*,*) ' NUM-INTERATION=',KK-1
	WRITE(*,*) ' ERROR         =',ERROR
	WRITE(*,*) ' EPS_BICGSTAB  =',EPS_BICGSTAB
	WRITE(*,*) ' SOLUTION IS DIVERGED! FAILURE IN SOLUTION! '
	PAUSE
    STOP		
END IF

END SUBROUTINE SOLUTION_BICGS_ALE
!
!
!
!
!
SUBROUTINE PRECON_GCM_ALE ( AP,EAP,EAPT,IEAPT,JEAPT )    !没看
USE VARIABLE,ONLY: N1DA_ALE,NN_ALE,IA_ALE,JA_ALE
USE CONSTANT,ONLY: WMGA
IMPLICIT NONE

REAL(8):: AP(N1DA_ALE),EAP(N1DA_ALE),EAPT(N1DA_ALE)
INTEGER:: IEAPT(NN_ALE+1),JEAPT(N1DA_ALE),I,K,J,J1,J2,M,NUMNODE

INTEGER,ALLOCATABLE:: NL(:)
REAL(8),ALLOCATABLE:: DAP(:)

ALLOCATE( NL(NN_ALE), DAP(NN_ALE) )

NUMNODE=NN_ALE

DO I=1,NUMNODE
K=IA_ALE(I+1)-1
EAP(K)=DSQRT(AP(K)) 
DAP(I)=EAP(K)      
END DO

NL=0   
DO I=1,NUMNODE 
J1=IA_ALE(I)
J2=IA_ALE(I+1)-1  
	DO J=J1,J2 
	K=JA_ALE(J)
	NL(K)=NL(K)+1		   
		IF(J /= J2) THEN   
		EAP(J)=WMGA*AP(J)/DAP(K)			
		END IF
	END DO
END DO

IEAPT(1)=1
DO I=1,NUMNODE
IEAPT(I+1)=IEAPT(I)+NL(I)
NL(I)=0
END DO

DO I=1,NUMNODE
	DO J=IA_ALE(I),IA_ALE(I+1)-1
	K=JA_ALE(J)
	NL(K)=NL(K)+1
	M=IEAPT(K)+NL(K)-1
	EAPT(M)=EAP(J)
	JEAPT(M)=I
	END DO
END DO

END SUBROUTINE PRECON_GCM_ALE





SUBROUTINE CHOLESKY_ALE(XXX,BBB,MARKER,EAP,EAPT,IEAPT,JEAPT)   !没看
USE VARIABLE,ONLY: NN_ALE,N1DA_ALE,IA_ALE,JA_ALE
IMPLICIT NONE

INTEGER:: I,J1,J2,J,K,MARKER
REAL(8):: XXX(NN_ALE), BBB(NN_ALE),EAP(N1DA_ALE),A,EAPT(N1DA_ALE)
INTEGER:: IEAPT(NN_ALE+1),JEAPT(N1DA_ALE)

REAL(8),ALLOCATABLE::YYY(:)
ALLOCATE(YYY(NN_ALE))

YYY(1)=BBB(1)/EAP(IA_ALE(1))
DO I=2,NN_ALE         
A=0.0D0
J1=IA_ALE(I)          
J2=IA_ALE(I+1)-2
	DO J=J1,J2
	K=JA_ALE(J)
	A=A+EAP(J)*YYY(K)
	END DO
YYY(I)=(BBB(I)-A)/EAP(J2+1)
END DO

IF (MARKER==1) THEN
XXX=YYY
RETURN
END IF

XXX(NN_ALE)=YYY(NN_ALE)/EAPT(IEAPT(NN_ALE))

DO I=NN_ALE-1,1,-1
A=0.0
J1=IEAPT(I)+1
J2=IEAPT(I+1)-1
	DO J=J1,J2
	K=JEAPT(J)
	A=A+EAPT(J)*XXX(K)
	END DO
XXX(I)=(YYY(I)-A)/EAPT(J1-1)               
ENDDO  

END SUBROUTINE CHOLESKY_ALE
!
!
!
!
SUBROUTINE COEFFICIENTMATRIX

USE CONSTANT 
USE VARIABLE
IMPLICIT NONE

INTEGER :: I,J,K,L,M,IE,NET(4),NK,NAF1,NAF2,JJ,NAF,MM,NPP,NODE
REAL(8) :: A1(4,4),A2(10),FD,Q,F1(4),ROU,G(4)


DO IE=1,NE
A2=0.0D0   	
A1=0.0D0
!	A4=0.0D0
NET(1:4)=NODEELE(IE,1:4)  
	  
	DO I=1,2  
		DO J=1,2
				
			CALL GAUSS_JACOB(I,J,IE)
		    FD=XPDKSI11*YPDITA22-XPDITA21*YPDKSI12 !J雅可比矩阵
			      
			IF ( FD < 0.0D0) THEN 
				WRITE(*,*)' ERROR : IE=',IE      
					DO K=1,4                       
					L=NET(K)                     
					WRITE(*,*) L,X(L),Y(L)  
					END DO                        
				WRITE(*,*) I,J,XPDKSI11,YPDITA22,XPDITA21,YPDKSI12,FD 
			END IF 
   
			Q=FD*WEI(I)*WEI(J)   

			DO K=1,4		   
			FPDX(K)=(YPDITA22*FPDKSI(I,J,K)-YPDKSI12*FPDITA(I,J,K))/FD
			FPDY(K)=(XPDKSI11*FPDITA(I,J,K)-XPDITA21*FPDKSI(I,J,K))/FD
			END DO

			DO K=1,4
				M=(K*(K-1))/2 							  
				DO L=1,K       
				A2(M+L)=A2(M+L)+F(I,J,K)*F(I,J,L)*Q                 ! LUMP MASS单元  N-S方程左边系数？？？？M=(K*(K-1))/2   A2(M+L)
				END DO

!					DO M=1,4
!					A4(K,M)=A4(K,M)+F(I,J,K)*F(I,J,M)*Q                 ! FULL MASS
!					END DO
			END DO

			DO K=1,4
				DO L=1,4
				A1(K,L)=A1(K,L)+Q*(FPDX(K)*FPDX(L)+FPDY(K)*FPDY(L)) ! PRESSURE POISSON单元 泊松方程左边系数
				END DO
			END DO
					 
		END DO
	END DO


	F1(1)=A2(1)+A2(2)+A2(4)+A2(7 )
	F1(2)=A2(2)+A2(3)+A2(5)+A2(8 ) 
	F1(3)=A2(4)+A2(5)+A2(6)+A2(9 )
	F1(4)=A2(7)+A2(8)+A2(9)+A2(10)


	DO K=1,4
	NK=NET(K)
	AM(NK)=AM(NK)+F1(K) ! LUMP MASS   整体     N-S方程
	END DO


	ROU=DENSITY
	A1=A1/ROU*DT     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
				
	DO K=1,4
	M=NET(K) 
	NAF1=IA(M)
	NAF2=IA(M+1)-1
		DO L=1,4
		JJ=NET(L)	   
			DO NAF=NAF1,NAF2
			MM=JA(NAF) 		  
				IF (MM==JJ) THEN
				NPP=NAF
				AP(NPP)=AP(NPP)+A1(K,L) ! POISSON EQUATION   整体  泊松
				END IF
			END DO
		END DO
	END DO
END DO
AP=AP*THETA(1)
!write(*,*) ap(100),ap(1000),ap(10000)
END SUBROUTINE COEFFICIENTMATRIX
